### ISSUE TITLE
Code of Conduct

### ISSUE THREAD

**Issue by andygrunwald** [WebEngDUS/WebEngDUS#1]
### Idea
Add a code of conduct to this repository. This code of conduct should be applied to our meetups

### Examples
* http://berlincodeofconduct.org/de/
* https://typo3.org/community/code-of-conduct/
* http://jsconf.com/codeofconduct.html
* a lot of other conferences out there

### Questions
* Is there any special on a meetup that don't apply on a conference that should be included?

### Further resources
Github has native support for code of conducts. See https://help.github.com/articles/adding-a-code-of-conduct-to-your-project/

**Comment by timglabisch** [comment]
more examples:

- https://github.com/rosarior/Code-of-Merit/blob/master/CODE_OF_MERIT.md
- https://github.com/timglabisch/code_of_conduct

**Comment by andygrunwald** [comment]
Another one (see below): https://weuceu.org/#
