### ISSUE TITLE
Speaker Guide

### ISSUE THREAD

**Issue by dsiebel** [WebEngDUS/WebEngDUS#7]
To not having to send out the same e-mail to speakers over and over again we could create a Speakers Guide containing all relevant information.

This idea is based on the great speakers guide from the Up.front UG:
http://up.front.ug/speakers-guide/

Information covered:
* thanks and introduction
* required information
  * speaker's contact info
  * title of the talk
  * abstract of the talk
* talk requirements
  * duration
  * language
  * how to handle questions
  * recruiting and advertising during the talk
* location, equipment and schedule
* code of conduct
* contact information of the meetup organisers
* encouragement :)

**Comment by andygrunwald** [comment]
Sadly, the link http://up.front.ug/speakers-guide/ is not working anymore.

I feel https://github.com/WebEngDUS/WebEngDUS/pull/23 solves this.

Do you agree @dsiebel ?
